# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee9220395e80393cce3bcb97aac8004b01bd4f3e3cecba5796883feaa19e564fbcc38aa6fc9ce088db0d43e7d81bb21225c9992ae3ae845479ac93129da459e

test:
  secret_key_base: a2121b07a062ae18c1fb689d66f23876b920cd5873a489da9479c6a7057315363013b52ae175bac212ee9dec2bb4143e9a11cc357ecc2ea65ca1377e24e40204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
